### PR TITLE
Remove duplication

### PR DESCRIPTION
**Pull request by maurolepore**
This PR removes duplication and adds tests.

* There is now a single copy of `translate()` in the entire package -- in data/data.R (see 
https://github.com/maurolepore/datos/blob/dry/data/data.R).

* The output of all translated datasets is now verified in tests/  (see https://github.com/maurolepore/datos/blob/dry/tests/testthat/output-translated-data.txt)

### CODE REVIEW

**Comment by maurolepore** [comment]
On Travis I see one check that fails; but the other two pass: https://travis-ci.org/github/cienciadedatos/datos/builds/702936760

I now use GitHub Actions more than Travis. I'll can see that in my fork: https://github.com/maurolepore/datos/actions

**Comment by maurolepore** [comment]
FYI, this PR passes ‘check_win_devel()’


https://win-builder.r-project.org/j4Suw8DhBypr

**Comment by rivaquiroga** [comment]
Thanks!
This mean that the call to `delayedAssign("object-name-in-spanish", translate("dataset.yml"))` should be added manually to `data.R` each time a new dataset is added to the package? That part of the `data_script()` function is valuable. I'll prefer not to loose it.

**Comment by maurolepore** [comment]
Oh, I see; so that’s what ‘data_script()’ was about. I didn’t see it called from anywhere, so I though it was dead code; but instead it is a helper to be used interactively, right?

Hold on then; I will restore it, and adapt it to the current code. But soon I think we could move ‘translate()’ and that helper to another, lower level package — as I think we discussed before.

**Comment by maurolepore** [comment]
Also I need  to confirm that it’s valid to use none-base packages in data/data.R.

**Comment by maurolepore** [comment]
This is my version of the helper. It only prints to code to the console, which you can then paste into data/data.R. This follows the usethis style -- a style we could use to build several other helpers. Now data/data.R also has the code of translate(), which is beyond the scope of this simple helper.

Another alternative would be to imitate `usethis::use_buildignore()`. So you would do something like `datos:::use_delayed_translate("airlines.yml")` to append data/data.R with `delayedAssign("aerolineas", translate("airlines.yml"))`.


What do you think?


``` r
datos:::use_delayed_translate()
#> delayedAssign("aerolineas", translate("airlines.yml"))
#> delayedAssign("aeropuertos", translate("airports.yml"))
#> delayedAssign("atmosfera", translate("atmos.yml"))
#> delayedAssign("premios_dirigentes", translate("awardmanagers.yml"))
#> delayedAssign("nombres", translate("babynames.yml"))
#> delayedAssign("bateadores", translate("batting.yml"))
#> delayedAssign("comunes", translate("common.yml"))
#> delayedAssign("diamantes", translate("diamonds.yml"))
#> delayedAssign("fiel", translate("faithful.yml"))
#> delayedAssign("jardineros", translate("fielding.yml"))
#> delayedAssign("vuelos", translate("flights.yml"))
#> delayedAssign("paises", translate("gapminder.yml"))
#> delayedAssign("encuesta", translate("gss-cats.yml"))
#> delayedAssign("flores", translate("iris.yml"))
#> delayedAssign("dirigentes", translate("managers.yml"))
#> delayedAssign("millas", translate("mpg.yml"))
#> delayedAssign("mtautos", translate("mtcars.yml"))
#> delayedAssign("personas", translate("people.yml"))
#> delayedAssign("lanzadores", translate("pitching.yml"))
#> delayedAssign("aviones", translate("planes.yml"))
#> delayedAssign("presidencial", translate("presidential.yml"))
#> delayedAssign("salarios", translate("salaries.yml"))
#> delayedAssign("tabla1", translate("table1.yml"))
#> delayedAssign("tabla2", translate("table2.yml"))
#> delayedAssign("tabla3", translate("table3.yml"))
#> delayedAssign("tabla4a", translate("table4a.yml"))
#> delayedAssign("tabla4b", translate("table4b.yml"))
#> delayedAssign("tabla5", translate("table5.yml"))
#> delayedAssign("vehiculos", translate("vehicles.yml"))
#> delayedAssign("clima", translate("weather.yml"))
#> delayedAssign("oms", translate("who.yml"))
```

<sup>Created on 2020-06-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
The last two commits fix a mistake of mine. I had intended to revert the commit that adds GitHub Actions but intstead reverted d293588. I now restore d293588 and revert the commit that adds GH Actions -- because I pushed it in a separate PR.

**Comment by maurolepore** [comment]
Above I said that I would confirm that it’s valid to use none-base packages in data/data.R. 

It think it is valid, as long as we do "not change the search() path by attaching packages or other environments (full quote below)." This is consistent with R CMD check not complaining about we now using a bunch of packages in the body of `translate()` in data/data.R. It also means we could eventually define `translate()` in another package, publish it on CRAN, then call it from data/data.R in the datos package. But for now I think this PR is valuable enougth -- as it removes duplicated instances of `trasnlate()` and overall removes a large number of code lines.

image


--

> Note that R code should be if possible “self-sufficient” and not make use of extra functionality provided by the package, so that the data file can also be used without having to load the package or its namespace: it should run as silently as possible and not change the search() path by attaching packages or other environments. -- https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages

**Comment by rivaquiroga** [comment]
`data_script()` do two things:
- creates the txt files in `inst/scripts`
- appends `delayedAssign(...` to `data.R`

This means that whether you add or edit one or more `.yml` files from `inst/specs`, you just have to run that function one time to update the package. 

My main issue with the proposed change is that having to copy/paste from the console --or appending one dataset at a time ( `datos:::use_delayed_translate("airlines.yml")`)--  makes the process slower and introduces the possibility of human error.

**Comment by maurolepore** [comment]
Thanks!

* in this PR, inst/scripts is no longer necessary. 

* I’ll try draft a version that directly updates data/data.R.

**Comment by rivaquiroga** [comment]
Yes, I know `inst/scripts` is not needed anymore, but as long as `data.R` is not directly updated, this PR makes the package less easy to maintain. 
I'm finishing the semester this week & the next; after that I can take a look and try to adapt `data_script()` to make it do what we expect.

**Comment by rivaquiroga** [comment]
Como nos cambiamos de la rama master a main, automáticamente se cerró este PR. Pero la idea es reabrirlo cuando podamos dedicar el tiempo necesario para resolver este asunto.

**Pull request closed without merging**
